### ISSUE TITLE
Issue in Notes for Designing Data Intensive Applications Book

### ISSUE THREAD

**Issue by abdulmoizabid** [SanDiegoMachineLearning/bookclub#3]
The notes for chapter 1 of the book Designing Data-Intensive Applications are inaccessible.

**Comment by congchan** [comment]
same issue here? any fix?

**Comment by tedkyi** [comment]
Hmm, Google flagged the content in the chapter 1 notes as spam???  I requested the content moderation team review it but don't know how long (if ever) they will complete the review.  I have tried creating a link to a new document to solve the problem.
