### ISSUE TITLE
UDL Errata

### ISSUE THREAD

**Issue by udlbook** [SanDiegoMachineLearning/bookclub#4]
Thrilled that you are reading my book and very grateful for the support.  Just wanted to warn you that there are quite a few errata in section 15.2 (part of the GANs chapter). They are fixed in the online version and in the second printing of the book, but if you are working from the first printed copy, it's worth looking at the errata.   The rest of the book is mostly fine.  

Please let me know if you find any other errata or if you have any other feedback. I'm working hard to fix everything and making notes on how to improve the second edition.

Simon

**Comment by tedkyi** [comment]
Thank you for sharing about the errata. We thoroughly enjoyed reading the UDL book.
